name: Deploy Angular App

on:
  push:
    branches:
      - master  # Deploy on every commit to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Deploy Angular App
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        ssh -i ~/.ssh/id_ed25519 $SERVER_USER@$SERVER_IP << 'EOF'
          set -e  # Exit immediately if a command fails
          cd /home/ubuntu/sample-angular-app  # Change to your project directory
          git pull origin master  # Pull latest changes
          sudo npm install --legacy-peer-deps   # Install dependencie
          sudo ng serve --host 0.0.0.0 --port 4200 &
          
          sudo npm run build --prod  # Build the Angular app
          # Move build files to web server directory
          sudo rm -rf /var/www/html/*
          sudo cp -r dist/* /var/www/html/
        EOF
        - name: Verify App Deployment
        run: |
        curl --retry 5 --retry-delay 5 --max-time 9 http://${{ secrets.SERVER_IP }}:4200
      
